# Generated by Django 5.1.6 on 2025-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('contrasena', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
