# Generated by Django 5.1.6 on 2025-02-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
