# Generated by Django 5.1.6 on 2025-02-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuarios_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='mail',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='carrera',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='matricula',
            field=models.CharField(default='SIN_MATRICULA', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='semestre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
